server:
  port: 8090

app:
  upload:
    dir: uploads/images
    video-dir: uploads/videos
  cors:
    allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:5175

spring:
  application:
    name: oshpaz-backend-system
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 205MB
  datasource:
    url: jdbc:postgresql://localhost:5432/chef
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  jackson:
    deserialization:
      fail-on-unknown-properties: false
#    serialization:
#      write-dates-as-timestamps: false
    default-property-inclusion: non_null

security:
  jwt:
    secret-key: ${SECRET_KEY:f72456084250dd5fa5b18eafffe4cdc1dbdcb36fa0e3608eb85d13b67705ce44}
    expiration-time: 86400000
    refresh-expiration-time: 604800000


